export const TEXT = {
  TITLE: "Automation Exercise",
  NEW_USER_SIGNUP: "New User Signup!",
  ACCOUNT_INFORMATION: "ENTER ACCOUNT INFORMATION",
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
};
